# This file is automatically generated from traits.build
# package, via the file remake.yml.whisker:
# edit the file there (or the files that it includes).

# Load R resources
library(traits.build)

# Load data resources
schema <- get_schema()
resource_metadata <- get_schema("config/metadata.yml", "metadata")
definitions <- get_schema("config/traits.yml", "traits")
unit_conversions <- get_unit_conversions("config/unit_conversions.csv")
taxon_list <- read_csv_char("config/taxon_list.csv")

# Build each source
Brouwer_2016_config <- dataset_configure("data/Brouwer_2016/metadata.yml", definitions)
Brouwer_2016_raw <- dataset_process("data/Brouwer_2016/data.csv", Brouwer_2016_config, schema, resource_metadata, unit_conversions)
Brouwer_2016 <- dataset_update_taxonomy(Brouwer_2016_raw, taxon_list)

Chiam_2019_config <- dataset_configure("data/Chiam_2019/metadata.yml", definitions)
Chiam_2019_raw <- dataset_process("data/Chiam_2019/data.csv", Chiam_2019_config, schema, resource_metadata, unit_conversions)
Chiam_2019 <- dataset_update_taxonomy(Chiam_2019_raw, taxon_list)

Chong_2010_config <- dataset_configure("data/Chong_2010/metadata.yml", definitions)
Chong_2010_raw <- dataset_process("data/Chong_2010/data.csv", Chong_2010_config, schema, resource_metadata, unit_conversions)
Chong_2010 <- dataset_update_taxonomy(Chong_2010_raw, taxon_list)

Chong_2011_config <- dataset_configure("data/Chong_2011/metadata.yml", definitions)
Chong_2011_raw <- dataset_process("data/Chong_2011/data.csv", Chong_2011_config, schema, resource_metadata, unit_conversions)
Chong_2011 <- dataset_update_taxonomy(Chong_2011_raw, taxon_list)

Lai_2020_config <- dataset_configure("data/Lai_2020/metadata.yml", definitions)
Lai_2020_raw <- dataset_process("data/Lai_2020/data.csv", Lai_2020_config, schema, resource_metadata, unit_conversions)
Lai_2020 <- dataset_update_taxonomy(Lai_2020_raw, taxon_list)

Lai_2020_2_config <- dataset_configure("data/Lai_2020_2/metadata.yml", definitions)
Lai_2020_2_raw <- dataset_process("data/Lai_2020_2/data.csv", Lai_2020_2_config, schema, resource_metadata, unit_conversions)
Lai_2020_2 <- dataset_update_taxonomy(Lai_2020_2_raw, taxon_list)

Lai_2020_3_config <- dataset_configure("data/Lai_2020_3/metadata.yml", definitions)
Lai_2020_3_raw <- dataset_process("data/Lai_2020_3/data.csv", Lai_2020_3_config, schema, resource_metadata, unit_conversions)
Lai_2020_3 <- dataset_update_taxonomy(Lai_2020_3_raw, taxon_list)

Lai_2021_config <- dataset_configure("data/Lai_2021/metadata.yml", definitions)
Lai_2021_raw <- dataset_process("data/Lai_2021/data.csv", Lai_2021_config, schema, resource_metadata, unit_conversions)
Lai_2021 <- dataset_update_taxonomy(Lai_2021_raw, taxon_list)

Metcalfe_1995_config <- dataset_configure("data/Metcalfe_1995/metadata.yml", definitions)
Metcalfe_1995_raw <- dataset_process("data/Metcalfe_1995/data.csv", Metcalfe_1995_config, schema, resource_metadata, unit_conversions)
Metcalfe_1995 <- dataset_update_taxonomy(Metcalfe_1995_raw, taxon_list)

Ng_2017_config <- dataset_configure("data/Ng_2017/metadata.yml", definitions)
Ng_2017_raw <- dataset_process("data/Ng_2017/data.csv", Ng_2017_config, schema, resource_metadata, unit_conversions)
Ng_2017 <- dataset_update_taxonomy(Ng_2017_raw, taxon_list)

Soo_2010_config <- dataset_configure("data/Soo_2010/metadata.yml", definitions)
Soo_2010_raw <- dataset_process("data/Soo_2010/data.csv", Soo_2010_config, schema, resource_metadata, unit_conversions)
Soo_2010 <- dataset_update_taxonomy(Soo_2010_raw, taxon_list)

Yee_2014_config <- dataset_configure("data/Yee_2014/metadata.yml", definitions)
Yee_2014_raw <- dataset_process("data/Yee_2014/data.csv", Yee_2014_config, schema, resource_metadata, unit_conversions)
Yee_2014 <- dataset_update_taxonomy(Yee_2014_raw, taxon_list)


SGtraits_raw <- austraits::bind_databases(
  Brouwer_2016,
  Chiam_2019,
  Chong_2010,
  Chong_2011,
  Lai_2020,
  Lai_2020_2,
  Lai_2020_3,
  Lai_2021,
  Metcalfe_1995,
  Ng_2017,
  Soo_2010,
  Yee_2014,
  NULL)

# Version information
version_number <- util_get_version("config/metadata.yml")
git_SHA <- util_get_SHA()

# Combine all the source into one resource
SGtraits <- build_add_version(SGtraits_raw, version_number, git_SHA)

# Save to file
dir.create("export/data/curr", FALSE, TRUE)
saveRDS(SGtraits, "export/data/curr/SGtraits.rds")
