metadata:
  title: 'SGtraits: a living trait database for the Singapore flora'
  description: "Work in progress"
  version: "0.0.2"
  doi: unknown
  geo_location:
    geo_location_place: Singapore
    geodetic_datum: EPSG:4326
  language: en
  related_identifiers:
  - related_identifier_type: url 
    identifier: https://github.com/hrlai/SGtraits.build
    relation_type: Compiles
    resource_type: dataset
  - related_identifier_type: doi
    identifier: .na
    relation_type: isCitedBy
    resource_type: publication-article  
  - related_identifier_type: doi
    identifier: .na
    relation_type: isVersionOf
    resource_type: dataset
  references: unknown
  publisher: Zenodo
  publication_year: 2025
  publication_date: unknown
  license:
    rights: CC-BY-4.0    
    rights_holder: Lai, Hao Ran
    rights_URI: https://creativecommons.org/licenses/by/4.0/
    description: Under this license, the material can be copied and redistributed in any medium or format. It can be remixed, transformed, and built upon for any purpose, even commercially. Re-users must give appropriate credit, provide a link to the license, and indicate if changes were made. Re-users may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
  funding_reference:
  - funder_name: unknown
    award_IRI: unknown
    award_number: unknown
    award_title: unknown
  creators: 
  - last_name: Lai
    given_name: Hao Ran
    ORCID: 0000-0001-6871-0146
    affiliation: South East Asia Rainforest Research Partnership, Malaysia
  contributors: .na
